name: pett_autonomy_service
author: pettai
version: 0.1.0
description: 'Pett.ai autonomous agent service for managing virtual pets'
aea_version: '>=2.0.0, <3.0.0'
license: Apache-2.0
fingerprint: {}
fingerprint_ignore_patterns: []
agent: pettai/pett_autonomy_agent:0.1.0
number_of_agents: 4
deployment:
  agent:
    ports:
      8000: 8000
      9000: 9000
      26656: 26656
      26657: 26657
---
public_id: pettai/pett_autonomy_service:0.1.0
type: service
network: ethereum
ledger_api:
  ethereum:
    address: https://ethereum-rpc.publicnode.com
    chain_id: 1
    gas_price_strategy: eip1559
off_chain_service_data:
  # Service configuration data
  service_name: 'Pett Autonomy Service'
  description: 'Multi-agent service for managing virtual pets on Pett.ai platform'
  capabilities:
    - 'Virtual pet management'
    - 'WebSocket communication with Pett.ai'
    - 'Multi-agent consensus'
    - 'Blockchain integration'
deployment_config:
  # Environment variables for the service
  env_vars:
    WEBSOCKET_URL: 'wss://petbot-monorepo-websocket-333713154917.europe-west1.run.app'
    NODE_ENV: 'production'
    LOG_LEVEL: 'INFO'
  # Resource limits
  resources:
    cpu: '0.5'
    memory: '512Mi'
  # Health checks
  health_check:
    port: 8000
    path: '/health'
    interval: 30
    timeout: 10
    retries: 3
