agent_name: pett_agent
author: pettaidev
version: 0.1.0
license: Apache-2.0
description: Pett.ai autonomous agent for virtual pet management on Olas SDK.
aea_version: '>=1.0.0, <3.0.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections: []
contracts: []
protocols: []
skills: []
customs: []
default_ledger: base
required_ledgers:
- base
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  disable_existing_loggers: false
  version: 1
dependencies:
  open-aea-ledger-cosmos:
    version: ==1.63.0
  open-aea-ledger-ethereum:
    version: ==1.63.0
default_connection: null
