agent_name: pett_autonomy_agent
author: pettai
version: 0.1.0
license: Apache-2.0
description: 'Pett.ai autonomous agent for Open Autonomy framework'
aea_version: '>=2.0.0, <3.0.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
  - valory/abci:0.1.0:bafybeic7zxihkwgcvqj2ajfdhuhxwcv6gqfizgqbhkm6k4vhgmpxzpkdxi
  - valory/http_client:0.23.0:bafybeiepv4n6hqcvawepgkh5x6kzcayxlpqdmj7ffs4afvk2mpejqt52nq
  - valory/ledger:0.19.0:bafybeicgkznuhhw5g6bk44w6vqlm4wg2frcpqgj6hpmr4zcnbgdlx7wttq
contracts:
  - valory/gnosis_safe:0.1.0:bafybeig6uuvlw3vwsrjppkyifezxz4jbrh5k6k3x5x4bh7bppsyj7mhwou
  - valory/gnosis_safe_proxy_factory:0.1.0:bafybeih3x6gdvdvzkftpckp62oqagkayzbxkq6qc3v73t7g6mz6lwc3f2a
  - valory/multisend:0.1.0:bafybeig3u3fhh5b2fzikrtdnzw4p6lffjnbknacl2mzj52b3oqhqghmkge
protocols:
  - open_aea/signing:1.0.0:bafybeib7p5as3obcdzseiwg5umj2piiqaodkxkto7qh7b552l5emwsmdzm
  - valory/abci:0.1.0:bafybeigzj6bhkqgqe3s3q52y4hqh5lhzntpe67fbmgfcj44hs6l6bm7fj4
  - valory/contract_api:1.0.0:bafybeid5cksazkuhqlihaxn5v5rqjjzx44xzswb4yy4hwcptfzz5eimu4u
  - valory/http:1.0.0:bafybeihaul6jxjywtc3z7r5xnfyufzllpjgdxjjxlstqpd3mxpxjpx5kcq
  - valory/ledger_api:1.0.0:bafybeijw6oaytx2kqqyeul5gxczlhm6z5qhqeymfktibgbk6g3qhmlx444
skills:
  - pettai/pett_agent_skill_abci:0.1.0
default_connection: valory/abci:0.1.0:bafybeic7zxihkwgcvqj2ajfdhuhxwcv6gqfizgqbhkm6k4vhgmpxzpkdxi
default_ledger: ethereum
required_ledgers:
  - ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  version: 1
  disable_existing_loggers: false
  formatters:
    standard:
      format: '[%(asctime)s] [%(levelname)s] %(message)s'
  handlers:
    logfile:
      class: logging.handlers.RotatingFileHandler
      formatter: standard
      filename: ${LOG_FILE:str:log.txt}
      maxBytes: 10485760
      backupCount: 10
    console:
      class: logging.StreamHandler
      formatter: standard
      stream: ext://sys.stdout
  loggers:
    aea:
      handlers:
        - logfile
        - console
      propagate: false
  root:
    level: ${LOG_LEVEL:str:INFO}
dependencies:
  open-autonomy: ==0.21.1
  open-aea: ==2.0.5
  open-aea-ledger-ethereum: ==2.0.5
---
public_id: pettai/pett_autonomy_agent:0.1.0
type: agent
